### ISSUE TITLE
Missing expect messages

### ISSUE THREAD

**Issue by MartinPilny** [crlnnn/demo-review#1]
There are many missing expect messages at primitive type comparisons in https://github.com/crlnnn/demo-review/blob/main/cypress/integration/productQuantity.spec.js
F.e.
https://github.com/crlnnn/demo-review/blob/bf7badefd0c441280cc79c8b9b0d0de83c830d57/cypress/integration/productQuantity.spec.js#L4

**Comment by crlnnn** [comment]
Primitive see, primitive do.
